
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:demo
    driver-class-name: org.h2.Driver
    username: demo
    password: demo
    sql-script-encoding: UTF-8

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update